---
title: "Hiato do produto no R"
theme: theme.css
draft: true
description: |
  A short description of the post.
author:
  - name: Felipe O. Gonçalves
date: 02-27-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r, include=FALSE}
options(scipen = 999)
```
Texto...

## Pacotes

Discussão sobre `devtools::install_github()`...
```{r, include=FALSE}
c("wilsonfreitas/rbcb", "kaushikrch/rucm", "KevinKotze/tsm")
```

```{r, message=FALSE}
library(rbcb)       # API do Banco Central
library(lubridate)  # objeto de tempo
library(mFilter)    # Hodrick-Prescott
library(rucm)       # Componentes Não Observados
library(tsm)        # Beveridge-Nelson
#
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Dados do produto

```{r, message=FALSE}
library(dplyr)

df_fgv <- "xgdvConsulta.csv" %>%
  read.csv2(encoding = "latin1") %>%
  as_tibble() %>%
  rename_all(~ c("date", "gdp")) %>%
  mutate(date = lubridate::my(date))

tail(df_fgv, 12)
```

## Trends determinísticos

```{r}
pred_levels <- function(x) {
  x %>%
    lm() %>% 
    fitted() %>%
    exp()
}
```

```{r}
df1 <- df_fgv %>%
  mutate(
    #
    t = row_number(),
    #
    .linear = pred_levels(log(gdp) ~ t),
    .quadratic = pred_levels(log(gdp) ~ t + I(t^2)),
    #
    avg_trend = (.linear + .quadratic) / 2
  )
```

```{r}
plot_p_gdp1 <- df1 %>%
  pivot_longer(
    c(.linear, .quadratic, avg_trend),
    names_to = "method",
    values_to = "index"
  ) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = index, color = method), linetype = "twodash", size = .75) +
  geom_line(aes(y = gdp))
```

### Figura 1: \ \ \ PIB vs. PIB Potencial \ (Trends Determinísticos)
```{r, echo=FALSE}
plot_p_gdp1 +
  labs(subtitle = "Número-Índice") +
  scale_y_continuous(limits = c(100, 200)) +
  ggthemes::scale_color_stata(
    labels = c("Linear", "Quadrático", "Combinação")
  ) +
  ggthemes::theme_clean() +
  theme(plot.background = element_blank(),
        plot.subtitle = element_text(hjust = -.06, size = 11),
        axis.title = element_blank(),
        axis.text = element_text(size = 10),
        axis.line.y = element_blank(),
        legend.title = element_blank(),
        legend.position = c(.875, .2),
        legend.background = element_blank())
```

## Filtros

$$\min_{\tau_1\ ...\ \tau_T} \sum_{t=1}^T{(y_t - \tau_t)}^2 + \lambda \sum_{t=2}^{T-1}{[(\tau_{t+1} - \tau_t)(\tau_t - \tau_{t-1})]}^2$$

```{r, message=FALSE}
df2 <- df_fgv %>%
  mutate(
    cubic_spline = log(gdp) %>%
      smooth.spline(df = 4) %>%
      .$y %>%
      exp(),
    hodrick_prescott = log(gdp) %>%
      mFilter::hpfilter(freq = 14400) %>%
      .$trend %>%
      .[,1] %>%
      exp()
  )
```

```{r}
plot_p_gdp2 <- df2 %>%
  pivot_longer(
    c(cubic_spline, hodrick_prescott),
    names_to = "method",
    values_to = "index"
  ) %>%
  #filter(lubridate::year(date) > 2013) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = index, color = method), linetype = "twodash", size = .75) +
  geom_line(aes(y = gdp))
```

### Figura 2: \ \ \ PIB vs. PIB Potencial \ (Filtros)
```{r, echo=FALSE}
plot_p_gdp2 +
  labs(subtitle = "Número-Índice") +
  scale_y_continuous(limits = c(100, 200)) +
  ggthemes::scale_color_stata(
    labels = c("Cubic Spline", "Hodrick-Prescott")
  ) +
  ggthemes::theme_clean() +
  theme(plot.background = element_blank(),
        plot.subtitle = element_text(hjust = -.06, size = 11),
        axis.title = element_blank(),
        axis.text = element_text(size = 10),
        axis.line.y = element_blank(),
        legend.title = element_blank(),
        legend.position = c(.875, .2),
        legend.background = element_blank())
```

## Decomposições

```{r, eval=FALSE}
df3 <- mutate(df_fgv, log_gdp = log(gdp))

x <- stl()

x <- rucm::ucm(log_gdp ~ 0, data = df3, slope = TRUE)
plot(1:252, exp(x$s.level))
str(x, max.level = 1)

df3 %>%
  mutate(
    unobs_components = rucm::ucm(log_gdp ~ 0, slope = TRUE, data = .) %>%
      .$s.level %>%
      as.numeric() %>%
      exp()
  ) %>%
  select(-log_gdp) %>%
  pivot_longer(-date) %>%
  ggplot(aes(date, value, color)) +
  geom_line()
```

```{r}
#x <- ts(df3$log_gdp, start = c(2000, 1), frequency = 12)
#X <- data.frame(x = x)

#UCM <- rucm::ucm(formula = x~0, data = X, level = TRUE)

#plot(X$x)
#lines(UCM$s.level, col = "blue")

log_diff_gdp <- ts(df_fgv$gdp, start = c(2000, 1), frequency = 12)
x <- rucm::ucm(log_diff_gdp ~ 0, data = log_diff_gdp, level.var = 2)
#plot(Nile)
plot(log_diff_gdp)
lines(rucm::ucm(log_diff_gdp ~ 0, data = log_diff_gdp)$s.level, col = "blue")
```


## Hiato do produto

## Uma regra de Taylor simples

[Histórico de metas de inflação](https://www.bcb.gov.br/controleinflacao/historicometas).

```{r}
targets <- c(6, 4, 3.5,           # 2000-02 (FHC II)
             4, 5.5, 4.5, 4.5,    # 2003-06 (Lula I)
             4.5, 4.5, 4.5, 4.5,  # 2007-10 (Lula II)
             4.5, 4.5, 4.5, 4.5,  # 2001-14 (Dilma I)
             4.5, 4.5,            # 2015-16 (Dilma II)
             4.5, 4.5,            # 2017-18 (Temer)
             4.25, 4)             # 2019-20 (Bolsonaro)
```

```{r}
pull_bacen <- function(x, y) {
  x %>%
    rbcb::get_series(first(y), last(y)) %>%
    pull(2)
}
```

```{r, eval=FALSE}
taylor <- df_fgv %>%
  mutate(
    #
    ipca = pull_bacen(13522, date),
    #
    ipca_target = targets %>%
      map(~ rep(.x, 12)) %>%
      flatten_dbl(),
    #
    selic = pull_bacen(4189, date)
  )
```